// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';

export function AddTodo(arg1:string):Promise<todo.Todo>;

export function GetTodos():Promise<Array<todo.Todo>>;

export function RemoveTodo(arg1:string):Promise<void>;

export function UpdateTodo(arg1:todo.TodoUpdate):Promise<todo.Todo>;
