// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function RemoveTodo(arg1) {
  return window['go']['main']['App']['RemoveTodo'](arg1);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
